version: '3'

services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "12345:12345"
    volumes:
      - ../server_data:/app/server_data
    restart: unless-stopped
    environment:
      - QT_LOGGING_RULES=*.debug=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 